In [8]:
import pandas as pd

from LPatternIdentification import feature_set, split_data, get_patterns_from_feature_set, reduce_pattern_set

In [3]:
# Load dataset
df = pd.read_csv('USPresidency.csv', index_col=0)
df.head(10)

      Q1  Q2  Q3  Q4  Q5  Q6  Q7  Q8  Q9  Q10  Q11  Q12  Target
Year
1864   0   0   0   0   1   0   0   1   1    0    0    0       1
1868   1   1   0   0   0   0   1   1   1    0    1    0       1
1872   1   1   0   0   1   0   1   0   0    0    1    0       1
1880   1   0   0   1   0   0   1   1   0    0    0    0       1
1888   0   0   0   0   1   0   0   0   0    0    0    0       1
1900   0   1   0   0   1   0   1   0   0    0    0    1       1
1904   1   1   0   0   1   0   1   0   0    0    1    0       1
1908   1   1   0   0   0   1   0   1   0    0    0    0       1
1916   0   0   0   0   1   0   0   1   0    0    0    0       1
1924   0   1   1   0   1   0   1   1   0    1    0    0       1

In [4]:
# Separate observations and labels
observations = df.iloc[:,:-1].to_numpy(dtype='int8')
labels = list(df['Target'])

In [7]:
# Find set of relevant features
elections_feature_set = feature_set(observations, labels)
elections_feature_set

[0, 2, 3, 5, 6, 7, 8, 11]

In [11]:
# Split observations and labels by class
split_point, Good, Bad = split_data(observations, labels)

In [12]:
# Return set of feature patterns corresponding to Good
Patterns = get_patterns_from_feature_set(Good, elections_feature_set)
Patterns

array([['0', '*', '0', '0', '*', '0', '0', '0', '0', '*', '*', '0'],
       ['0', '*', '0', '0', '*', '0', '0', '1', '0', '*', '*', '0'],
       ['0', '*', '0', '0', '*', '0', '0', '1', '1', '*', '*', '0'],
       ['0', '*', '0', '0', '*', '0', '1', '0', '0', '*', '*', '0'],
       ['0', '*', '0', '0', '*', '0', '1', '0', '0', '*', '*', '1'],
       ['0', '*', '0', '0', '*', '1', '1', '1', '0', '*', '*', '0'],
       ['0', '*', '1', '0', '*', '0', '1', '1', '0', '*', '*', '0'],
       ['1', '*', '0', '0', '*', '0', '1', '0', '0', '*', '*', '0'],
       ['1', '*', '0', '0', '*', '0', '1', '1', '0', '*', '*', '0'],
       ['1', '*', '0', '0', '*', '0', '1', '1', '1', '*', '*', '0'],
       ['1', '*', '0', '0', '*', '1', '0', '1', '0', '*', '*', '0'],
       ['1', '*', '0', '0', '*', '1', '1', '1', '0', '*', '*', '0'],
       ['1', '*', '0', '1', '*', '0', '1', '1', '0', '*', '*', '0'],
       ['1', '*', '1', '0', '*', '0', '0', '1', '0', '*', '*', '0']],
      dtype='<U1')

In [13]:
# Reduce patterns to uniquely Good patterns
Patterns_reduced = reduce_pattern_set(Patterns, Bad, 7)
Patterns_reduced

array([['0', '*', '0', '0', '*', '0', '0', '*', '*', '*', '*', '0'],
       ['0', '*', '0', '0', '*', '0', '1', '0', '0', '*', '*', '*'],
       ['1', '*', '0', '0', '*', '0', '1', '*', '*', '*', '*', '0'],
       ['1', '*', '0', '0', '*', '1', '0', '1', '0', '*', '*', '0'],
       ['*', '*', '0', '0', '*', '1', '1', '1', '0', '*', '*', '0'],
       ['1', '*', '0', '1', '*', '0', '1', '1', '0', '*', '*', '0'],
       ['*', '*', '1', '0', '*', '0', '*', '1', '0', '*', '*', '0']],
      dtype='<U1')